MVCNedir/Areas/AdminPanel/Controllers/BrandController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MVCNedir.Filters;
using MVCNedir.Models;

namespace MVCNedir.Areas.AdminPanel.Controllers
{
    [AdminPanelAuthenticationFilter]
    public class BrandController : Controller
    {
        private AdimAdimDBModel db = new AdimAdimDBModel();

        // GET: AdminPanel/Brand
        public ActionResult Index()
        {
            return View(db.Brands.ToList());
        }

        // GET: AdminPanel/Brand/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Brand brand = db.Brands.Find(id);
            if (brand == null)
            {
                return HttpNotFound();
            }
            return View(brand);
        }

        // GET: AdminPanel/Brand/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: AdminPanel/Brand/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Isim")] Brand brand)
        {
            if (ModelState.IsValid)
            {
                db.Brands.Add(brand);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(brand);
        }

        // GET: AdminPanel/Brand/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Brand brand = db.Brands.Find(id);
            if (brand == null)
            {
                return HttpNotFound();
            }
            return View(brand);
        }

        // POST: AdminPanel/Brand/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Isim")] Brand brand)
        {
            if (ModelState.IsValid)
            {
                db.Entry(brand).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(brand);
        }

        // GET: AdminPanel/Brand/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Brand brand = db.Brands.Find(id);
            if (brand == null)
            {
                return HttpNotFound();
            }
            return View(brand);
        }

        // POST: AdminPanel/Brand/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Brand brand = db.Brands.Find(id);
            db.Brands.Remove(brand);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MVCNedir/Areas/AdminPanel/Controllers/CategoryController.cs
using MVCNedir.Filters;
using MVCNedir.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCNedir.Areas.AdminPanel.Controllers
{
    [AdminPanelAuthenticationFilter]
    public class CategoryController : Controller
    {
        AdimAdimDBModel db = new AdimAdimDBModel();
        
        public ActionResult Index()
        {
            List<Category> categories = db.Categories.ToList();
            return View(categories);
        }

        [HttpGet]//Sayfa açılırken bu metot çalışır
        public ActionResult Ekle()
        {
            return View();
        }

        //Sayfada herhangi bir işlem yapıldığında Örn Butona Basıldığında bu metot çalışır
        [HttpPost]
        public ActionResult Ekle(Category c)
        {
            if (ModelState.IsValid)
            {
                db.Categories.Add(c);
                db.SaveChanges();
            }
            else
            {
                return View(c);
            }

            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult Duzenle(int? id)
        {
            if (id== null)
            {
                return RedirectToAction("Index");
            }
            Category c = db.Categories.Find(id);
            if (c== null)
            {
                return RedirectToAction("Index");
            }
            return View(c);
        }
        [HttpPost]
        public ActionResult Duzenle(Category c)
        {
            if (ModelState.IsValid)
            {
                db.Entry(c).State = System.Data.Entity.EntityState.Modified;
                //Category old = db.Categories.Find(c.ID);
                //old.Isim = c.Isim;
                //old.Aciklama = c.Aciklama;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(c);
        }
        public ActionResult Sil(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");
            }
            Category c = db.Categories.Find(id);
            if (c == null)
            {
                return RedirectToAction("Index");
            }
            db.Categories.Remove(c);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

MVCNedir/Areas/AdminPanel/Controllers/ProductController.cs
using MVCNedir.Filters;
using MVCNedir.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCNedir.Areas.AdminPanel.Controllers
{
    [AdminPanelAuthenticationFilter]
    public class ProductController : Controller
    {
        AdimAdimDBModel db = new AdimAdimDBModel();
        // GET: AdminPanel/Product
        public ActionResult Index()
        {
            return View(db.Products.ToList());
        }
        public ActionResult IndexActiveProduct()
        {
            return View(db.Products.Where(x => x.SellStatus == true).ToList());
        }

        [HttpGet]
        public ActionResult Create()
        {
            ViewBag.Category_ID = new SelectList(db.Categories, "ID", "Isim");
            ViewBag.Brand_ID = new SelectList(db.Brands, "ID", "Isim");
            return View();
        }

        [HttpPost]
        public ActionResult Create(Product model, HttpPostedFileBase resim)
        {
            if (ModelState.IsValid)
            {
                if (resim != null)
                {
                    FileInfo fi = new FileInfo(resim.FileName);
                    if (fi.Extension == ".jpg" || fi.Extension == ".png" || fi.Extension == ".jpeg")
                    {
                        string isim = Guid.NewGuid().ToString() + fi.Extension;
                        model.ImagePath = isim;
                        resim.SaveAs(Server.MapPath("~/ProductImages/" + isim));
                    }
                    else
                    {
                        model.ImagePath = "noneproduct.jpg";
                    }
                }
                else
                {
                    model.ImagePath = "noneproduct.jpg";
                }
                model.CreationTime = DateTime.Now;
                db.Products.Add(model);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Category_ID = new SelectList(db.Categories, "ID", "Isim");
            ViewBag.Brand_ID = new SelectList(db.Brands, "ID", "Isim");
            return View(model);
        }

        [HttpGet]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");
            }
            Product p = db.Products.Find(id);
            ViewBag.Category_ID = new SelectList(db.Categories, "ID", "Isim", p.Category_ID);
            ViewBag.Brand_ID = new SelectList(db.Brands, "ID", "Isim", p.Brand_ID);
            return View(p);
        }
        [HttpPost]
        public ActionResult Edit(Product p, HttpPostedFileBase resim)
        {
            if (ModelState.IsValid)
            {
                db.Entry(p).State = System.Data.Entity.EntityState.Modified;

                if (ModelState.IsValid)
                {
                    if (resim != null)
                    {
                        FileInfo fi = new FileInfo(resim.FileName);
                        if (fi.Extension == ".jpg" || fi.Extension == ".png" || fi.Extension == ".jpeg")
                        {
                            string isim = Guid.NewGuid().ToString() + fi.Extension;
                            p.ImagePath = isim;
                            resim.SaveAs(Server.MapPath("~/ProductImages/" + isim));
                        }
                        else
                        {
                            p.ImagePath = "noneproduct.jpg";
                        }
                    }
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            ViewBag.Category_ID = new SelectList(db.Categories, "ID", "Isim", p.Category_ID);
            ViewBag.Brand_ID = new SelectList(db.Brands, "ID", "Isim", p.Brand_ID);
            return View(p);
        }
        public ActionResult Delete(int id)
        {
            Product p = db.Products.Find(id);
            p.SellStatus = false;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

MVCNedir/Areas/AdminPanel/Views/Shared/_LayoutPage1.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.3/font/bootstrap-icons.css">
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/dashboard.css" rel="stylesheet" />
</head>
<body class="d-flex flex-column h-100">

    <header class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
        <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3" href="@Url.Action("Index","Home")">adimadim.com Admin Panel</a>
        <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-nav">
            <div class="nav-item text-nowrap">
                <a class="nav-link px-3" href="#">Çıkış</a>
            </div>
        </div>
    </header>
    <main class="flex-shrink-0">
        <div class="container-fluid">
            <div class="row">
                <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
                    <div class="position-sticky pt-3">
                        <ul class="nav flex-column">
                            <li class="nav-item">
                                <a class="nav-link" aria-current="page" href="@Url.Action("Index","Home")">
                                    <span data-feather="home"></span>
                                    Anasayfa
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" aria-current="page" href="@Url.Action("Index","Category")">
                                    <span data-feather="home"></span>
                                    Kategori İşlemleri
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" aria-current="page" href="@Url.Action("Index","Brand")">
                                    <span data-feather="home"></span>
                                    Marka İşlemleri
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" aria-current="page" href="@Url.Action("Index","Product")">
                                    <span data-feather="home"></span>
                                    Tüm Ürünler
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" aria-current="page" href="@Url.Action("IndexActiveProduct","Product")">
                                    <span data-feather="home"></span>
                                    Satıştaki Ürünler
                                </a>
                            </li>
                        </ul>

                        <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
                            <span>Ayarlar</span>
                            <a class="link-secondary" href="#" aria-label="Add a new report">
                                <span data-feather="plus-circle"></span>
                            </a>
                        </h6>
                        <ul class="nav flex-column mb-2">
                            <li class="nav-item">
                                <a class="nav-link" href="#">
                                    <span data-feather="file-text"></span>
                                    Kullanıcı Ayarları
                                </a>
                            </li>
                        </ul>
                    </div>
                </nav>

                <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
                    @RenderBody()
                </main>
                
            </div>
        </div>
    </main>
    <footer class="footer py-3 bg-light fixed-bottom">
        <div class="container-fluid">
            <span class="text-muted">Place sticky footer content here.</span>
        </div>
    </footer>
   
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>